k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: gke_adahealth-consumer-dev_europe-west1-b_consumer-test
  currentCluster: gke_adahealth-consumer-dev_europe-west1-b_consumer-test
  clusters:
    arn:aws:eks:me-south-1:566495590731:cluster/client-stg-bh:
      namespace:
        active: ""
        favorites:
        - all
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_adahealth-client-dev-pjzknt_europe-west1-b_client-istio-1-11-4:
      namespace:
        active: default
        favorites:
        - all
        - default
        - istio-system
        - furiosa-zuul
        - kube-public
        - auth-admin
        - test-demo
        - demo-assessment-bff
      view:
        active: ctx
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_adahealth-client-dev_europe-west1-b_client-test:
      namespace:
        active: ""
        favorites:
        - campaign-signup-be
        - care-navigation-bff
        - website-next
        - kube-system
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_adahealth-consumer-dev_europe-west1-b_consumer-stg:
      namespace:
        active: default
        favorites:
        - all
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_adahealth-consumer-dev_europe-west1-b_consumer-test:
      namespace:
        active: istio-system
        favorites:
        - istio-system
        - axaone-stg
        - default
        - demo-assessment-report-service
        - demo-hcp-report-fe
        - demo-smart-auth
        - demo-medical-profile
        - deprecated-content-service
        - all
      view:
        active: context
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_adahealth-consumer-prod_europe-west1_consumer-prod-eu:
      namespace:
        active: ""
        favorites:
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_adahealth-infra-dev_europe-west1-b_infra-eu:
      namespace:
        active: default
        favorites:
        - demo-assessment-bff
        - all
        - default
      view:
        active: ctx
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_rd-kumo-teamday-v002_europe-west1_teamday:
      namespace:
        active: fixme
        favorites:
        - fixme
        - default
      view:
        active: ns
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_ts-2900-scheduling-policies_us-central1-c_cluster-1:
      namespace:
        active: poc
        favorites:
        - poc
        - all
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    kp-sandbox-aks:
      namespace:
        active: ""
        favorites:
        - test-demo
        - all
        - default
      view:
        active: gw
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    ts-1482-surls-aks:
      namespace:
        active: default
        favorites:
        - default
      view:
        active: ctx
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
