plugin:
  get-all:
    shortCut: g
    confirm: false
    description: Get All
    scopes:
      - all
    command: sh
    background: false
    # In the namespace scope, use $NAME instead of $NAMESPACE
    args:
      - -c
      - "watch -n 2 \"kubectl --context $CONTEXT --namespace $([[ $NAMESPACE == \"-\" ]] && echo $NAME || echo $NAMESPACE) get all | less\""
  # watch-events:
  #   shortCut: Shift-E
  #   confirm: false
  #   description: Events
  #   scopes:
  #   - all
  #   command: sh
  #   background: false
  #   args:
  #   - -c
  #   - "watch -n 2 \"kubectl get events --context $CONTEXT --namespace $NAMESPACE --field-selector involvedObject.name=$NAME --field-selector involvedObject.kind=$SCOPE | less\""
  # stern: # get logs of running containers (Istio excluded) with stern
  #   shortcut: Shift-S
  #   confirm: false
  #   description: Stern
  #   scopes:
  #   - deployment
  #   command: sh
  #   background: false
  #   args:
  #   - c
  #   - "stern --namespace $NAMESPACE --exclude-container \"istio-[a-z]+\" --field-selector status.phase=Running $NAME"
