plugin:
  #get all resources in a namespace using the krew get-all plugin
  get-all:
    shortCut: g
    confirm: false
    description: Get All
    scopes:
      - all
    command: sh
    background: false
    args:
      - -c
      - "watch -n 1 \"kubectl --context $CONTEXT --namespace $([[ $NAMESPACE == \"-\" ]] && echo $NAME || echo $NAMESPACE) get all | less\""
