# $XDG_CONFIG_HOME/k9s/views.yaml
# Press `w` in a view to show remaining default columns after these.
views:
  v1/nodes:
    sortColumn: NODEGROUP:desc
    columns:
      - NAME
      - STATUS
      - PODS
      - CPU
      - "%CPU"
      - MEM
      - "%MEM"
      - NODEGROUP:.metadata.labels.eks\.amazonaws\.com/nodegroup
      - NODEPOOL:.metadata.labels.karpenter\.sh/nodepool
      - AGE
